framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    http_method_override: true
    session:
        handler_id: snc_redis.session.handler
        gc_probability: 1
        gc_divisor: 100
    php_errors:
        log: true
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: snc_redis.cache
        prefix_seed: vairogs
