nelmio_api_doc:
    documentation:
        info:
            title: '%vairogs.title%'
            description: '%vairogs.subtitle%'
            version: '%vairogs.version%'
    areas:
        path_patterns:
            - ^/api(?!/doc$)
#        host_patterns:
#            - ^api\.
