nelmio_api_doc:
    documentation:
        info:
            title: Vairogs
            description: Real Latvian CMS
            version: 0.0.1
    areas:
        path_patterns:
            - ^/api(?!/doc$)
