security:
    providers:
        in_memory:
            memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler(?!/(phpinfo|open))|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
    access_control:
        -
            path: ^/_profiler/(phpinfo|open)
            roles: ROLE_PHPINFO
        -
            path: ^/admin
            roles: ROLE_ADMIN
