snc_redis:
    clients:
        default:
            type: predis
            alias: session
            dsn:
                - '%env(resolve:REDIS_URL1)%'
                - '%env(resolve:REDIS_URL2)%'
            options:
                connection_persistent: true
                replication: sentinel
                service: mymaster
                throw_errors: true
                parameters:
                    database: 10
                prefix: vairogs_session_
            logging: false
        cache:
            type: predis
            alias: cache
            dsn:
                - '%env(resolve:REDIS_URL1)%'
                - '%env(resolve:REDIS_URL2)%'
            options:
                connection_persistent: true
                replication: sentinel
                service: mymaster
                throw_errors: true
                parameters:
                    database: 11
                prefix: vairogs_cache_
            logging: false
        meta:
            type: predis
            alias: meta
            dsn:
                - '%env(resolve:REDIS_URL1)%'
                - '%env(resolve:REDIS_URL2)%'
            options:
                connection_persistent: true
                replication: sentinel
                service: mymaster
                throw_errors: true
                parameters:
                    database: 12
                prefix: vairogs_meta_
            logging: false
        guzzle:
            type: predis
            alias: guzzle
            dsn:
                - '%env(resolve:REDIS_URL1)%'
                - '%env(resolve:REDIS_URL2)%'
            options:
                connection_persistent: true
                replication: sentinel
                service: mymaster
                throw_errors: true
                parameters:
                    database: 14
                prefix: vairogs_guzzle_
            logging: true
        cluster:
            type: predis
            alias: cluster
            dsn:
                - '%env(resolve:REDIS_URL1)%'
                - '%env(resolve:REDIS_URL2)%'
            options:
                connection_persistent: true
                replication: sentinel
                service: mymaster
                throw_errors: true
                parameters:
                    database: 13
                prefix: vairogs_cluster_
            logging: false
    session:
        client: session
        prefix: session_vairogs_
    doctrine:
        metadata_cache:
            client: meta
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
