snc_redis:
    clients:
        default:
            type: predis
            alias: session
            dsn: '%env(resolve:REDIS_URL)%/10'
            options:
                connection_persistent: true
                prefix: vairogs_session_
            logging: true
        cache:
            type: predis
            alias: cache
            dsn: '%env(resolve:REDIS_URL)%/11'
            options:
                connection_persistent: true
                prefix: vairogs_cache_
            logging: true
        meta:
            type: predis
            alias: meta
            dsn: '%env(resolve:REDIS_URL)%/12'
            options:
                connection_persistent: true
                prefix: vairogs_meta_
            logging: true
    session:
        client: session
        prefix: session_vairogs_
    doctrine:
        metadata_cache:
            client: meta
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: default
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
