#vairogs:
#    utils:
#        translatable: true
#        core:
#            php_functions:
#                - random_int
#        guzzle:
#            profiler: "%kernel.debug%"
#            logger: "%kernel.debug%"
#            redis_client: snc_redis.guzzle
#            cache:
#                adapter: vairogs.utils.guzzle.cache_adapter.redis
