parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\Guzzle:
        arguments:
            -
                verify: false
                exceptions: false
                on_stats:
                    - '@vairogs.utils.guzzle.data_collector.history_bag'
                    - 'addStats'
        tags:
            -
                name: vairogs.utils.guzzle.client
                middleware: '!cache'

